name: Workload Format Checker
on: [workflow_dispatch, pull_request]

jobs:
  custom-jinja2-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jq

          git clone https://github.com/aristanetworks/j2lint.git && cd j2lint
          # Developer mode only has extensions capability
          python3 -m pip install -e .

          # Ensure that version has extensions capability
          j2lint --version
          j2lint --help

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35

      - name: Run J2lint on changed JSON files in a pull-request
        if: github.event_name == 'pull_request'
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            if [[ $file == *.json ]]; then
              echo "Checking $file"
              j2lint "$GITHUB_WORKSPACE/$file" --extensions json --json
            fi
          done

      - name: Run J2lint on all JSON files in a branch
        if: github.event_name == 'workflow_dispatch'
        run: |
          chmod +x "$GITHUB_WORKSPACE/.github/j2_format_checker.sh"
          ./$GITHUB_WORKSPACE/.github/j2_format_checker.sh "$GITHUB_WORKSPACE"






